### ISSUE TITLE
Are you planning to release the dataset ? 

### ISSUE THREAD

**Issue by abduallahmohamed** [ishann/aeroscapes#1]
Btw, your work is great ! 

Are you planning to release the dataset ?  
Because I was unable to find it?

**Comment by ishann** [comment]
Thank you for your interest in Aeroscapes. We're caught up with other research commitments at the moment.

Aeroscapes will definitely be released, but we are not sure exactly when.

**Comment by ghost** [comment]
Looking forward to it!

**Comment by ghost** [comment]
Is there any estimation on when the dataset will be released?

**Comment by ishann** [comment]
The dataset has been released. Please check the last commit.
