### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by 4ever-Rain** [ishann/aeroscapes#3]
Hi! Thanks for your greet job! I couldn't download the dataset now. I think the URL"https://cmu.box.com/shared/static/ihp4huuw1sofgfjx9ov679jhx85hq9ib.gz" failed.

Can you update it?

@ishann

**Comment by ishann** [comment]
Hey, apologies for the delay in replying.
The data is now hosted on Google Drive. Please see the updated README.
